api/urls.py
from django.urls import path
from api import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api'

urlpatterns = [
    path('todo/', views.TodoListCreateView.as_view(), name='todo_list_create_api_view'), # list create todo
    path('todo/<int:id>/', views.TodoDetailView.as_view(), name='todo_detail_view'), # todo detail
    path('todo/<int:id>/delete/', views.TodoDestroyView.as_view(), name='todo_destroy_view'), # delete todo
    path('todo/<int:id>/update/', views.TodoUpdateView.as_view(), name='todo_update_view'), # update todo
    path('todo/<slug:category_slug>/', views.TodoCategoryListView.as_view(), name='todo_category_list_view'), # category based todo filtering url
    # Categories
    path('category/', views.CategoryListCreateView.as_view(), name='category_list_create_api_view'), # list create
    path('category/<int:id>/', views.CategoryDetailView.as_view(), name='category_detail_view'), # detail
    path('category/<int:id>/delete/', views.CategoryDeleteView.as_view(), name='category_delete_view'), # delete category
    path('category/<int:id>/update/', views.CategoryUpdateView.as_view(), name='category_update_view'), # update category
    # tokenization
    path('token/', obtain_auth_token, name='api_create_and_get_token'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from todo_app import views

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path("logout/", views.logout_view, name='logout'),
    path("signup/", views.signup_view, name='signup'),
    path('api/', include('api.urls')),
    path("admin/", admin.site.urls),
    path("", include('todo_app.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo_app/urls.py
from django.urls import path, include
from todo_app import views

app_name = "todo_app"

urlpatterns = [
    path('category/edit/<slug:category_slug>/', views.edit_category_view, name="category_edit"),
    path('category/delete/<slug:category_slug>/', views.delete_category_view, name="delete_category"),
    path("category/<slug:category_slug>/", views.category_detail_view, name="category_detail"),
    path("todo/new-todo/", views.todo_entry_view, name='todo_entry'),
    path("todo/edit/<slug:todo_slug>/", views.edit_todo_view, name="edit_todo"),
    path("todo/create-category/", views.create_category_view, name="create_category"),
    path("todo/<slug:todo_slug>/", views.todo_view, name="todo_view" ),
    path("todo/delete/<slug:todo_slug>/", views.delete_todo_view, name="delete_todo"),
    path("", views.home_view, name="home"),
    path("complete-todo/", views.complete_todo, name="complete_todo"),
    path('activate_task/', views.activate_task, name='activate_task'),

    #Profile
    path('profile/profile-update/', views.profile_edit_view, name='profile_update'),
    path('profile/delete-account/', views.delete_account_view, name="delete_account"),
    path('profile/<slug:profile_slug>/', views.profile_view, name='profile'),
]

todo_app/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from django.urls import reverse
import random, string

from django.utils.timezone import localtime

from slugify import slugify

# Base model
class BaseModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title', unique=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        abstract=True
        ordering=('title',)


class Category(BaseModel):
    created_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_abso_url(self):
        return reverse(
            'todo_app:category_detail',
            kwargs={
                "category_slug": self.slug
            }
        )


class Todo(BaseModel):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    content = tinymce_models.HTMLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_abso_url(self):
        return reverse(
            'todo_app:todo_view',
            kwargs={
                "todo_slug": self.slug
            }
        )
    
    class Meta:
        ordering = ('created_at',)

    def formatted_created_at(self):
        return localtime(self.created_at).strftime('%Y-%m-%d %H:%M')

    def formatted_updated_at(self):
        return localtime(self.updated_at).strftime('%Y-%m-%d %H:%M')


class Images(models.Model):
    image = models.ImageField(upload_to='todo-uploads/')



# Profile Model Section
def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=125, unique=True)
    is_active = models.BooleanField(default=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    description = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            if not Profile.objects.filter(slug=slugify(f"{self.user.username} {self.user.last_name}")).exists():
                self.slug = slugify(f"{self.user.username} {self.user.last_name}")
            else:
                self.slug = slugify(f"{self.user.username} {self.user.last_name} {rand_slug()}")
        super(Profile, self).save(*args, **kwargs)

    def get_abso_url(self):
        return reverse('todo_app:profile', kwargs={'profile_slug':self.slug})

todo_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Todo, Profile, Category
from django.core import validators
from tinymce.widgets import TinyMCE
import json

def validate_email_unique(value):
    if User.objects.filter(email=value).exists():
        raise forms.ValidationError("This Email is already registered. Please use different email. ")


class UserForm(forms.ModelForm):
    email = forms.EmailField(validators=[validators.EmailValidator(message='Please check your email format.'), validate_email_unique])
    password = forms.CharField(widget=forms.PasswordInput(), validators=[validators.MinLengthValidator(10, message='You need to write a minimum 10 character long password'),])

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username", # Django automatically validate uniqueness of usernames in database
            "email",
            "password",
        ]

class ProfileModelForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'avatar',
            'description',
        ]

class TodoModelForm(forms.ModelForm):

    content = forms.CharField(widget=TinyMCE(attrs={'cols': 100, 'rows': 20}))
    tag = forms.CharField(required=False)

    class Meta:
        model = Todo
        fields = [
            'title',
            'is_active',
            'category',
            'content',
            'tag',
        ]


class CategoryModelForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = [
            'title',
            'is_active',
        ]

todo_app/views.py
from django.shortcuts import render,redirect, get_object_or_404
from todo_app.models import Todo, Category, Profile
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import json
import random

#authentication
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

#forms
from .forms import UserForm, ProfileModelForm, TodoModelForm, CategoryModelForm

from django.views.generic.base import RedirectView

# Create your views here.

@login_required(login_url='/login/')
def home_view(request):
    todos = Todo.objects.filter(is_active=True, user=request.user)
    completed_todos = Todo.objects.filter(is_active=False, user=request.user)
    context = dict(todos=todos, completed_todos=completed_todos)
    return render(request, 'todo_app/homepage.html', context=context)


# New Todo
@login_required(login_url='/login/')
def todo_entry_view(request):
    form = TodoModelForm(request.POST or None)
    form.fields['category'].queryset = Category.objects.filter(user=request.user)
    context = dict(form=form, title='New Todo', button_info='Save')
    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        return redirect(reverse('todo_app:todo_view', kwargs={'todo_slug':form.slug}))
    return render(request, 'registration/form.html', context=context)



def complete_todo(request):
    if request.method == "POST" and 'checkbox' in request.POST:
            checkbox_todo = request.POST.getlist('checkbox')
            for checkbox in checkbox_todo:
                Todo.objects.filter(title=checkbox).update(is_active=False)
            return redirect(reverse('todo_app:home'))
    else:
        return redirect(reverse('todo_app:home'))

def activate_task(request):
     if request.method == "POST" and 'checkbox' in request.POST:
        checkbox_todo = request.POST.getlist('checkbox')
        for checkbox in checkbox_todo:
            Todo.objects.filter(title=checkbox).update(is_active=True)
        return redirect(reverse('todo_app:home'))
     else:
          return redirect(reverse('todo_app:home'))

# todo detail
@login_required(login_url='/login/')
def todo_view(request, todo_slug):
     todo = get_object_or_404(Todo,slug=todo_slug, user=request.user)
     context = dict(todo=todo)
     return render(request, "todo_app/todo_detail.html", context)

# Edit Todo
@login_required(login_url='/login/')
def edit_todo_view(request, todo_slug):
    todo = get_object_or_404(Todo, slug=todo_slug, user=request.user)
    form = TodoModelForm(request.POST or None, instance=todo)
    form.fields['category'].queryset = Category.objects.filter(user=request.user)
    context = dict(form=form, title='Edit Todo', button_info='Save')
    if form.is_valid():
        form.save() # formu değil artık objeyi kaydediyoruz.
        messages.success(request,"You've succesfully edited your Todo.")
        return redirect(reverse('todo_app:todo_view', kwargs={'todo_slug':todo_slug}))
    return render(request, 'registration/form.html', context=context)


# Delete Todo
@login_required(login_url='/login/')
def delete_todo_view(request,todo_slug):
    todo = get_object_or_404(Todo,slug=todo_slug, user=request.user)
    todo.delete()
    messages.success(request, 'Todo Has Been Deleted Succesfully.')
    return redirect('todo_app:home')

# Create New Category
@login_required(login_url='/login/')
def create_category_view(request):
    form = CategoryModelForm(request.POST or None)
    context = dict(form=form, title='New Category', button_info='Save')
    if form.is_valid():
        title = form.cleaned_data.get('title')
        obj, created = Category.objects.get_or_create(title=title, user=request.user) # If there is the same category in the database, it will return obj instead of create it.
        return redirect(reverse('todo_app:category_detail', kwargs={'category_slug':obj.slug}))
    return render(request, 'registration/form.html', context=context)

# Edit Category
@login_required(login_url='/login/')
def edit_category_view(request,category_slug):
    category = get_object_or_404(Category, slug=category_slug, user=request.user)
    form = CategoryModelForm(request.POST or None, instance=category)
    context = dict(form=form, title=f"{category.title} Edit", button_info='save')
    if form.is_valid():
        form.save()
        messages.success(request,"You've succesfully edited Category")
        return redirect(reverse('todo_app:category_detail', kwargs={'category_slug':category_slug}))
    return render(request, 'registration/form.html', context)


# Delete Category
@login_required(login_url='/login/')
def delete_category_view(request,category_slug):
    category = get_object_or_404(Category, slug=category_slug, user=request.user)
    category.delete()
    messages.success(request, 'Category Has Been Deleted Succesfully.')
    return redirect('todo_app:home')

        

# category detail
@login_required(login_url='/login/')
def category_detail_view(request, category_slug):
     category = get_object_or_404(Category, slug=category_slug)
     todos = Todo.objects.filter(is_active=True, category=category, user=request.user)
     context = dict(category=category, todos=todos)
     return render(request, 'todo_app/category_detail.html', context)
     
     
# login
def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('todo_app:home'))
    if request.method == 'POST':
        if request.POST['username'] != '' and request.POST['password'] != '':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password) # eğer alınan bilgiler doğruysa validate edilirse authenticate returns User object.
            if user is not None:
                login(request, user)
                messages.info(request, f'{user.username} You are succesfully logged in.')
                return redirect('todo_app:home')
            
            else:
                messages.warning(request, f'Username or Passsword Incorrect. Please check and try again.')
                return render(request, 'registration/login.html', context={})
        else:
            messages.info(request, 'Your Username or password is empty. Please check and try again !')
            return render(request, 'registration/login.html', {})
    else:
        return render(request, 'registration/login.html', context={})
     

# logout
def logout_view(request):
    if request.user.is_authenticated:
        messages.info(request,f'{request.user.username} You succesfully logged out.')
        logout(request)
        return redirect(reverse('logout'))
    else:
        if request.META.get('HTTP_REFERER'):
            return redirect(request.META['HTTP_REFERER'])
        return redirect('todo_app:home')
    

# Signup
def signup_view(request):
    form = UserForm(request.POST or None)
    if form.is_valid(): # if form is not valid then view works like get request.
        password = form.cleaned_data.get('password')
        form_user = form.save(commit=False) # returns User object -> Thanks to UserForm
        form_user.set_password(password)
        form_user.save()
        Profile.objects.create(user=form_user)
        messages.success(request, 'You registration is succesfully completed !')
        return redirect('todo_app:home')

    return render(request, 'registration/form.html', {'form':form, 'title':'Signup Form', 'button_info':'Register'})


@login_required(login_url='/login/')
def profile_view(request, profile_slug):
    profile = get_object_or_404(Profile, slug=profile_slug)
    context = dict(profile=profile)
    return render(request, 'todo_app/profile_detail.html', context)


@login_required(login_url='/login/')
def profile_edit_view(request):
    user = request.user
    user_data = dict(first_name = user.first_name, last_name=user.last_name)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=user.profile, initial=user_data) # None gelirse ProfileModelForm Boş olarak oluşur.
    context = dict(form=form, title=f'{user.username} Profile Edit', button_info='Update')
    if request.method == 'POST': 
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            form.save()
            messages.success(request,'Your profile has been updated.')
            return redirect(reverse('todo_app:profile', kwargs={'profile_slug':user.profile.slug}))
    return render(request, 'registration/form.html', context)


# Delete Account
@login_required(login_url='/login/')
def delete_account_view(request):
    user = get_object_or_404(User, username=request.user.username)
    if request.method == 'POST':
        if request.POST.get('number') and request.POST.get('number') == request.session['random_int']:
            user.delete()
            messages.warning(request, 'Your Account Has Been Deleted :(')
            return redirect('todo_app:home')
        else:
            messages.info(request, 'Wrong validation number. Please check the number above and try again.')
    random_int = random.randint(2500,10000)
    request.session['random_int'] = random_int
    context = dict(user=user, random_int=random_int)
    return render(request, 'registration/delete.html', context=context)
    

todo_app/templates/todo_app/category_detail.html
{%extends 'base.html'%}

{%block content%}

<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-sm-3 text-center">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    <a href="/category/edit/{{category.slug}}/"><li class="list-inline-item"><span class="badge rounded-pill text-bg-light">Edit</span></li></a>
                    <a href="/category/delete/{{category.slug}}/"><li class="list-inline-item"><span class="badge rounded-pill text-bg-warning">Delete</span></li></a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 offset-sm-3 mt-1 mb-3 text-center">
            {% if category %}
                <h1>{{category.title}} - ({{todos.count}})</h1>
            {%elif tag %}
                <h1>{{tag.title}} - ({{todos.count}})</h1>
            {%endif%}
        </div>
        <div class="col-sm-12 align-item-center ">
            <ul class="list-group">
                <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                <strong>{{ message }} </strong>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="col-sm-6 offset-sm-3">
                        {%for todo in todos%}
                            <li class="list-group-item list-group-item-action text-center" aria-current="true">
                                <a href="{{todo.get_abso_url}}" style="text-decoration: none;">
                                    <input type="checkbox" name="checkbox" value="{{todo.title}}" class="mx-2"> {{todo.title}}
                                </a>
                            </li>
                        {%endfor%}
                    </div>
                </div>
            </ul>
        </div>
    </div>
</div>

{%endblock content%}

todo_app/templates/todo_app/homepage.html
{% extends 'base.html'%}
 {%load static%}

{# The page that you list all your todo's  #}

{%block content%}
    <div class="container">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <strong>{{ message }} </strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% include 'todo_app/components/todo_list.html' %}

        <hr class="my-5">

        {%include 'todo_app/components/completed_tasks.html' %}

    </div>

{%endblock content%}

todo_app/templates/todo_app/profile_detail.html
{% extends 'base.html'%}


{%block content%}
<div class="container">
    <div class="row text-center">
        <div class="col-sm-12 col-lg-10">
            {# Breadcrumb #}
            <div class="col-sm-6 offset-sm-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{%url 'todo_app:home'%}">Home</a></li>
                    <li class="breadcrumb-item">{{profile.user.username}}</li>
                    </ol>
                </nav>
            </div>
            {# Breadcrumb END #}
            <div class="col-sm-6 offset-sm-3">
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        <strong>{{ message }} </strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="col-sm-6 offset-sm-3">
                <h1>
                    {{profile.user.username}} Profile
                </h1>
            </div>
            <div class="col-sm-6 offset-sm-3">
                {% include 'todo_app/components/avatar.html' %}
            </div>
            <div class="col-sm-6 offset-sm-3 mt-5">
                {{profile.description}}
            </div>
        </div>
        <div class="col-sm-10 offset-sm-1 col-lg-2 offset-lg-0 my-3 my-lg-0">
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'todo_app:profile_update' %}" class="link-light">Edit Profile</a></li>
                <li class="list-group-item"><a href="{%url 'todo_app:delete_account'%}" class="link-light">Delete Account</a></li>
              </ul>
        </div>
    </div>
</div>
{%endblock content%}

todo_app/templates/todo_app/todo_detail.html
{%extends 'base.html'%}

{%block content%}

<div class="container">
    <div class="row text-center">
        <div class="col-sm-6 offset-sm-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{%url 'todo_app:home'%}">Home</a></li>
                  {%if todo.category %}<li class="breadcrumb-item"><a href="{{todo.category.get_abso_url}}">{{todo.category.title}}</a></li> {%endif%}
                  <li class="breadcrumb-item active" aria-current="page">{{todo.title}}</li>
                </ol>
              </nav>
        </div>
        <div class="col-sm-6 offset-sm-3">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    <a href="/todo/edit/{{todo.slug}}/"><li class="list-inline-item"><span class="badge rounded-pill text-bg-light">Edit</span></li></a>
                    <a href="/todo/delete/{{todo.slug}}/"><li class="list-inline-item"><span class="badge rounded-pill text-bg-warning">Delete</span></li></a>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <h1>{{todo.title}}</h1>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <strong>{{ message }} </strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="col-sm-12 mt-3">
            {{todo.content|safe}}
        </div>
        <div class="col-sm-12 mt-3">
            {% include 'todo_app/components/profile_section.html' %}
        </div>
    </div>
</div>

{%endblock%}