api/urls.py
from django.urls import path
from api import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api'

urlpatterns = [
    path('todo/', views.TodoListCreateView.as_view(), name='todo_list_create_api_view'), # list create todo
    path('todo/<int:id>/', views.TodoDetailView.as_view(), name='todo_detail_view'), # todo detail
    path('todo/<int:id>/delete/', views.TodoDestroyView.as_view(), name='todo_destroy_view'), # delete todo
    path('todo/<int:id>/update/', views.TodoUpdateView.as_view(), name='todo_update_view'), # update todo
    path('todo/<slug:category_slug>/', views.TodoCategoryListView.as_view(), name='todo_category_list_view'), # category based todo filtering url
    # Categories
    path('category/', views.CategoryListCreateView.as_view(), name='category_list_create_api_view'), # list create
    path('category/<int:id>/', views.CategoryDetailView.as_view(), name='category_detail_view'), # detail
    path('category/<int:id>/delete/', views.CategoryDeleteView.as_view(), name='category_delete_view'), # delete category
    path('category/<int:id>/update/', views.CategoryUpdateView.as_view(), name='category_update_view'), # update category
    # tokenization
    path('token/', obtain_auth_token, name='api_create_and_get_token'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from todo_app import views

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path("logout/", views.logout_view, name='logout'),
    path("signup/", views.signup_view, name='signup'),
    path('api/', include('api.urls')),
    path("admin/", admin.site.urls),
    path("", include('todo_app.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo_app/urls.py
from django.urls import path, include
from todo_app import views

app_name = "todo_app"

urlpatterns = [
    path('category/edit/<slug:category_slug>/', views.edit_category_view, name="category_edit"),
    path('category/delete/<slug:category_slug>/', views.delete_category_view, name="delete_category"),
    path("category/<slug:category_slug>/", views.category_detail_view, name="category_detail"),
    path("todo/new-todo/", views.todo_entry_view, name='todo_entry'),
    path("todo/edit/<slug:todo_slug>/", views.edit_todo_view, name="edit_todo"),
    path("todo/create-category/", views.create_category_view, name="create_category"),
    path("todo/<slug:todo_slug>/", views.todo_view, name="todo_view" ),
    path("todo/delete/<slug:todo_slug>/", views.delete_todo_view, name="delete_todo"),
    path("", views.home_view, name="home"),
    path("complete-todo/", views.complete_todo, name="complete_todo"),
    path('activate_task/', views.activate_task, name='activate_task'),

    #Profile
    path('profile/profile-update/', views.profile_edit_view, name='profile_update'),
    path('profile/delete-account/', views.delete_account_view, name="delete_account"),
    path('profile/<slug:profile_slug>/', views.profile_view, name='profile'),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {%endblock title%} - Todo App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {%block pagecss%} {%endblock%}
</head>
<body>

    {% include 'navbar.html'%}


    <main>
        {%block content%}
        {%endblock content%}
    </main>
    

    {% include 'footer.html'%}


</body>
</html>

templates/navbar.html
{% load thumbnail %}
<header>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary p-3 mb-5 mt-1">
            <div class="container">
              <a class="navbar-brand" href="/">Todo App</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Categories
                    </a>
                    <ul class="dropdown-menu">
                      {% for cat in categories %}
                      <li><a class="dropdown-item" href="{{cat.get_abso_url}}">{% if cat.user == request.user %} {{cat.title}} {% endif %}</a></li>
                      {%endfor%}
                    </ul>
                  </li>
                  <li>
                    <a href="{%url 'todo_app:create_category'%}"class="nav-link">Create New Category</a>
                  </li>
                  <li>
                    <a href="{%url 'todo_app:todo_entry'%}"class="nav-link">Create New Todo</a>
                  </li>
                  {%endif%}
                </ul>

                <ul class="navbar-nav ms-auto">
                  {# Account Login - Logout Navigasyon #}
                  {% if not user.is_authenticated %}
                  <li>
                    <a href="{%url 'signup'%}" class="nav-link"> Sign-up</a>
                  </li>
                    <li>
                      <a href="{%url 'login' %}" class="nav-link">Sign in</a>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
                          <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5M.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5m15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5"/>
                          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                          </svg> Account
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{request.user.profile.get_abso_url}}">Profile</a></li>
                      </ul>
                    </li>
                    <li class="nav-item">
                      <a href="{%url 'logout' %}" class="nav-link">Logout</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
        </nav>
    </div>
</header>